; Dude Tax — maintenance page (Update/Repair vs Uninstall)
LangString addOrReinstall ${LANG_ENGLISH} "Update / Repair (overwrite program files, keep data)"
LangString alreadyInstalled ${LANG_ENGLISH} "Already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already installed.$\r$\nChoose an action and click Next.$\r$\n$\r$\n· Update/Repair: overwrite program files; your data is kept.$\r$\n· Uninstall: remove the app; data deletion is confirmed later."
LangString appRunning ${LANG_ENGLISH} "{{product_name}} is running! Please close it first then try again."
LangString appRunningOkKill ${LANG_ENGLISH} "{{product_name}} is running!$\nClick OK to end the process."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose Update/Repair or Uninstall"
LangString choowHowToInstall ${LANG_ENGLISH} "Choose Update to new version, or Uninstall"
LangString createDesktop ${LANG_ENGLISH} "Create desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Update / Repair (overwrite program files, keep data)"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Cannot downgrade (uninstall the newer version first)"
LangString failedToKillApp ${LANG_ENGLISH} "Failed to end {{product_name}}. Please close it first then try again."
LangString installingWebview2 ${LANG_ENGLISH} "Installing WebView2..."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of ${PRODUCTNAME} is already installed.$\r$\nInstalling an older version is not recommended. You can Update/Repair to overwrite, or Uninstall first."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "${PRODUCTNAME} is installed (current: $R4).$\r$\nThis package is version ${VERSION}.$\r$\n$\r$\nChoose:$\r$\n· Update/Repair: upgrade and keep your data (recommended)$\r$\n· Uninstall: remove the current app"
LangString silentDowngrades ${LANG_ENGLISH} "Downgrades are disabled for this installer; cannot proceed silently. Use the graphical installer.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Unable to uninstall!"
LangString uninstallApp ${LANG_ENGLISH} "Uninstall this program"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Update / Repair (overwrite program files, keep data)"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "Failed to install WebView2! The app can't run without it. Try restarting the installer."
LangString webview2DownloadError ${LANG_ENGLISH} "Error: Downloading WebView2 Failed - $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 bootstrapper downloaded successfully"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2 bootstrapper..."
LangString webview2InstallError ${LANG_ENGLISH} "Error: Installing WebView2 failed with exit code $1"
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 installed successfully"
LangString deleteAppData ${LANG_ENGLISH} "Also delete application data (including local database; irreversible)"
