; Dude Tax — 维护页文案（已安装时：更新/修复 vs 卸载）
LangString addOrReinstall ${LANG_SIMPCHINESE} "更新 / 修复安装（覆盖程序文件，保留数据）"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "检测到已安装"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "本机已安装 ${PRODUCTNAME} ${VERSION}。$\r$\n请选择要执行的操作，然后点击「下一步」。$\r$\n$\r$\n· 更新/修复：覆盖安装程序文件，不会删除您的业务数据。$\r$\n· 卸载：移除程序；是否删除数据将在卸载向导中另行确认。"
LangString appRunning ${LANG_SIMPCHINESE} "{{product_name}} 正在运行！请关闭后再试。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "{{product_name}} 正在运行！$\n点击「确定」以结束进程。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "请选择：更新/修复，或卸载"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "请选择：更新到新版本，或卸载当前版本"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "更新 / 修复安装（覆盖程序文件，保留数据）"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "无法降级（请先卸载当前更高版本）"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法结束 {{product_name}}。请手动关闭后再试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 WebView2..."
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "本机已安装更高版本的 ${PRODUCTNAME}。$\r$\n不建议安装旧版。若仍要继续，可选「更新/修复」覆盖，或先「卸载」当前版本。"
LangString older ${LANG_SIMPCHINESE} "旧"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "本机已安装 ${PRODUCTNAME}（当前版本：$R4）。$\r$\n安装包版本为 ${VERSION}。$\r$\n$\r$\n请选择：$\r$\n· 更新/修复：升级并覆盖程序文件，保留业务数据（推荐）$\r$\n· 卸载：移除当前程序"
LangString silentDowngrades ${LANG_SIMPCHINESE} "此安装程序已禁用降级，无法静默安装，请使用图形界面。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "无法卸载！"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载本程序"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "更新 / 修复安装（覆盖程序文件，保留数据）"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "无法安装 WebView2！应用依赖它才能运行。请重试安装程序。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "错误：无法下载 WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "WebView2 引导程序下载成功"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 WebView2 引导程序..."
LangString webview2InstallError ${LANG_SIMPCHINESE} "错误：安装 WebView2 失败，错误代码：$1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "WebView2 安装成功"
LangString deleteAppData ${LANG_SIMPCHINESE} "同时删除应用程序数据（含本地数据库，不可恢复）"
